openapi: 3.0.0
info:
  title: Moank Pay Invoice Flow API
  version: 1.0.0
  description: |
    Draft API - Invoice flow
servers:
- url: https://api.moankpay.com/1.0/
  description: Production server
- url: https://staging.api.moankpay.com/1.0/
  description: Staging server

paths:
  /credit-decision:
    post:
      tags:
      - Credit Decision
      summary: Create credit decision
      description: Apply for a credit decision for this customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - test
              properties:
                test:
                  type: string
                  description: Test
                  example: This is a test
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                - test
                properties:
                  test:
                    type: string
                    description: Test
                    example: This is a test
        400:
          $ref: "#/components/responses/dataError"
        401:
          $ref: "#/components/responses/authError"
        500:
          $ref: "#/components/responses/serverError"
        503:
          $ref: "#/components/responses/serviceError"
      security:
      - bearer_auth: []

components:
  responses:
    dataError:
      description: Invalid data
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/dataError"

    authError:
      description: Invalid authentication
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/authError"

    notFoundError:
      description: Application not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/notFoundError"

    serverError:
      description: Internal Server Error. If the problem persists contact the technical support
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/serverError"

    serviceError:
      description: Service Error. If the problem persists contact the technical support
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/serviceError"

  schemas:
    error:
      type: object
      required:
      - status
      - message
      - errors
      properties:
        status:
          type: integer
          description: HTTP status code
        message:
          type: string
          description: Main error reason
        errors:
          type: array
          description: List of errors messages to describe the issue in more details
          items:
            type: string

    dataError:
      allOf:
        - $ref: "#/components/schemas/error"
        - type: object
          properties:
            status:
              example: 400
            message:
              example: INVALID_REQUEST
            errors:
              type: array
              items:
                example: Field ... should be defined

    authError:
      allOf:
        - $ref: "#/components/schemas/error"
        - type: object
          properties:
            status:
              example: 401
            message:
              example: Unauthorized

    notFoundError:
      allOf:
        - $ref: "#/components/schemas/error"
        - type: object
          properties:
            status:
              example: 404
            message:
              example: Application not found

    serverError:
      allOf:
        - $ref: "#/components/schemas/error"
        - type: object
          properties:
            status:
              example: 500
            message:
              example: Internal Server Error

    serviceError:
      allOf:
        - $ref: "#/components/schemas/error"
        - type: object
          properties:
            status:
              example: 503
            message:
              example: Service unavailable

  securitySchemes:
    bearer_auth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
